--liquibase formatted sql

--changeset yevhenii:1
create table if not exists country(
    id int GENERATED BY DEFAULT AS IDENTITY not null ,
    code int not null ,
    primary key (id)
);

--changeset yevhenii:2
create table if not exists language(
    id int GENERATED BY DEFAULT AS IDENTITY not null ,
    localization varchar(255) not null ,
    primary key (id)
);

--changeset yevhenii:3
create table if not exists country_language(
    id int GENERATED BY DEFAULT AS IDENTITY not null ,
    country_id int not null ,
    language_id int not null ,
    translate varchar(255) not null ,
    primary key (id),
    foreign key (country_id) references country(id) ,
    foreign key (language_id) references language(id)
);
--changeset yevhenii:4
insert into country(code) values ('001'),('002');

--changeset yevhenii:5
insert into language(localization) values ('UK'),('RU'),('EN');

--changeset yevhenii:6
insert into country_language(translate, country_id, language_id) values ('Україна',1,1), ('Украина',1,2), ('Ukraine',1,3), ('Фінляндія',2,1), ('Финляндия',2,2), ('Finland', 2,3);
